#!/usr/bin/env bash
set -e

USER=team254
HOST=ec2.team254.com
APP=cheesy-hours
case "${1}" in
  --ftc) APP=ftc-hours ;;
  --frc|"") ;;
  *) echo "Usage: ./deploy [--frc|--ftc]" && exit 1 ;;
esac
SCRIPT_NAME=hours_server

echo "Deploying $APP..."
echo
ssh $USER@$HOST "cd /opt/sites/$APP && git pull && bundle install && bundle exec rake db:migrate && sudo -n /usr/bin/systemctl restart $APP.service"
echo
echo "Deployed $APP."
