source "https://rubygems.org"

gem "activesupport"
gem "cheesy-common", :git => "https://github.com/Team254/cheesy-common.git"
gem "daemons"
gem "httparty"
gem "mysql2"
gem "pathological"
gem "rake"
gem "sequel"
gem "sinatra"
gem "thin"
gem "tzinfo-data"
