source "https://rubygems.org"

gem "activesupport"
gem "aescrypt"
gem "daemons"
gem "httparty"
gem "mysql2"
gem "pathological"
gem "rake"
gem "sequel"
gem "sinatra"
gem "sinatra-websocket"
gem "thin"
